apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cbt-clusterrole
# csi-snapshot-session-access-clusterrole
rules:
# Split this into another yaml
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cbt.storage.k8s.io
  resources:
  - csisnapshotsessionaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - watch
