apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-snapshot-session-client
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: csi-snapshot-session-client-cluster-role
rules:
- apiGroups:
  - snapshot.storage.k8s.io
  resources:
  - volumesnapshots
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cbt.storage.k8s.io
  resources:
  - csisnapshotsessionaccesses
  verbs:
  - create
  - delete
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csi-snapshot-session-client-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: csi-snapshot-session-client-cluster-role
subjects:
- kind: ServiceAccount
  name: csi-snapshot-session-client  
  namespace: cbt-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: csi-snapshot-session-client
  name: csi-snapshot-session-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csi-snapshot-session-client
  template:
    metadata:
      labels:
        app: csi-snapshot-session-client
    spec:
      serviceAccountName: csi-snapshot-session-client
      containers:
      - image: prasadg193/sample-cbt-client:latest
        name: client
        command:
        - sh
        - -c
        - tail -f /dev/null
