FROM golang:1.19 as builder
WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
COPY pkg pkg
COPY ./cmd/client/main.go main.go
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o grpc-client main.go

FROM alpine
RUN apk add util-linux coreutils && apk update && apk upgrade
WORKDIR /
COPY --from=builder /workspace/grpc-client .
CMD ["tail", "/dev/null"]
