apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-snapshot-session-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: csi-snapshot-session-service-cluster-role
rules:
- apiGroups:
  - cbt.storage.k8s.io
  resources:
  - csisnapshotsessiondata
  - csisnapshotsessionservice
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: csi-snapshot-session-service-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: csi-snapshot-session-service-cluster-role
subjects:
- kind: ServiceAccount
  name: external-snapshot-session-service
  namespace: csi-driver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-snapshot-session-service
spec:
  selector:
    matchLabels:
      name: external-snapshot-session-service
  replicas: 1
  template:
    metadata:
      labels:
        name: external-snapshot-session-service
    spec:
      serviceAccountName: external-snapshot-session-service
      containers:
      - name: csi-hostpath-cbt-service
        image: prasadg193/sample-csi-cbt-service:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      - name: external-snapshot-session-service
        image: prasadg193/external-snapshot-session-service:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: server-certs
          mountPath: /tmp/certificates
          readOnly: true
        - mountPath: /csi
          name: socket-dir
        env:
        - name: CBT_SERVER_CERT
          value: "/tmp/certificates/tls.crt"
        - name: CBT_SERVER_KEY
          value: "/tmp/certificates/tls.key"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumes:
      - name: server-certs
        secret:
          secretName: ext-snap-session-svc-certs
      - hostPath:
          path: /var/lib/kubelet/plugins/cbt/csi-hostpath
          type: DirectoryOrCreate
        name: socket-dir
---
apiVersion: v1
kind: Service
metadata:
  name: external-snapshot-session-service
  labels:
    name: external-snapshot-session-service
spec:
  ports:
  - name: cbt
    port: 6443
    protocol: TCP
    targetPort: 9000
  selector:
    name: external-snapshot-session-service
